In [2]:
import pandas as pd
import numpy as np

In [2]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
fruits

['apple', 'orange', 'apple', 'apple', 'apple', 'orange', 'apple', 'apple']

In [3]:
N = len(fruits)
N

8

In [4]:
df = pd.DataFrame({'fruits': fruits,
                  'basket_id': np.arange(N),
                  'count': np.random.randint(3, 15, size=N),
                  'weight': np.random.uniform(0, 4, size=N)})
df

basket_id  count  fruits    weight
0          0     10   apple  0.401279
1          1      3  orange  0.702813
2          2      4   apple  0.718401
3          3     14   apple  2.423133
4          4     11   apple  0.709755
5          5     11  orange  1.237476
6          6      5   apple  0.116771
7          7      7   apple  1.110661

In [5]:
fruit_cat = df['fruits'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruits, dtype: category
Categories (2, object): [apple, orange]

In [9]:
fruit_cat.values.codes, fruit_cat.values.categories

(array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8),
 Index(['apple', 'orange'], dtype='object'))

In [10]:
df['fruits'] = df['fruits'].astype('category')
df, df.fruits.dtype

(   basket_id  count  fruits    weight
 0          0     10   apple  0.401279
 1          1      3  orange  0.702813
 2          2      4   apple  0.718401
 3          3     14   apple  2.423133
 4          4     11   apple  0.709755
 5          5     11  orange  1.237476
 6          6      5   apple  0.116771
 7          7      7   apple  1.110661,
 CategoricalDtype(categories=['apple', 'orange'], ordered=False))

In [ ]:
my_cat = pd.Categorical(['foo', 'bar', 'faz', 'foo', 'bar'])
my_cat

In [31]:
categories = ['foo', 'bar', 'baz']
codes = [0,1,2,0,1]
pd.Categorical.from_codes(codes, categories)


[foo, bar, baz, foo, bar]
Categories (3, object): [foo, bar, baz]

In [2]:
np.random.seed(12345)

In [3]:
draws = np.random.randn(1000)
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [5]:
bins = pd.qcut(draws, 4, labels=['Q1','Q2','Q3','Q4'])
bins

[Q2, Q3, Q2, Q2, Q4, ..., Q3, Q2, Q1, Q3, Q4]
Length: 1000
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [8]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [11]:
bins = pd.Series(bins, name='quartile')
bins[:10]

0    Q2
1    Q3
2    Q2
3    Q2
4    Q4
5    Q4
6    Q3
7    Q3
8    Q4
9    Q4
Name: quartile, dtype: category
Categories (4, object): [Q1 < Q2 < Q3 < Q4]

In [20]:
pd.Series(draws).groupby(bins).agg(['count','min','mean']).reset_index()

quartile  count       min      mean
0       Q1    250 -2.949343 -1.215981
1       Q2    250 -0.683066 -0.362423
2       Q3    250 -0.010032  0.307840
3       Q4    250  0.634238  1.261160

In [25]:
N = 10000000
draws = np.random.randn(N)
labels = pd.Series(['foo','bar','baz','qux'] * (N//4))

In [29]:
categories = labels.astype('category')
categories[:10]

0    foo
1    bar
2    baz
3    qux
4    foo
5    bar
6    baz
7    qux
8    foo
9    bar
dtype: category
Categories (4, object): [bar, baz, foo, qux]

In [30]:
labels.memory_usage(), categories.memory_usage()

(80000080, 10000272)

In [31]:
s = pd.Series(['a','b','c','d'] * 2)
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [32]:
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): [a, b, c, d]

In [33]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [34]:
cat_s.cat.as_unordered

<bound method PandasDelegate._add_delegate_accessors.<locals>._create_delegator_method.<locals>.f of <pandas.core.categorical.CategoricalAccessor object at 0x2b50d1759828>>

In [35]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [38]:
cat_s = cat_s.cat.add_categories(['e'])
cat_s.cat.categories

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [39]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [42]:
pd.get_dummies(pd.Series([1,2,3,2,3,4,2,3]))

1  2  3  4
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  1  0  0
4  0  0  1  0
5  0  0  0  1
6  0  1  0  0
7  0  0  1  0

In [43]:
df = pd.DataFrame({'key': ['a','b','c'] * 4,
                  'value': np.arange(12.)})
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [46]:
df.groupby('key').mean(), df.groupby('key').transform(lambda x: x.mean()), df.groupby('key').transform('mean')

(     value
 key       
 a      4.5
 b      5.5
 c      6.5,     value
 0     4.5
 1     5.5
 2     6.5
 3     4.5
 4     5.5
 5     6.5
 6     4.5
 7     5.5
 8     6.5
 9     4.5
 10    5.5
 11    6.5,     value
 0     4.5
 1     5.5
 2     6.5
 3     4.5
 4     5.5
 5     6.5
 6     4.5
 7     5.5
 8     6.5
 9     4.5
 10    5.5
 11    6.5)

In [51]:
df['rank'] = df['value'].rank()

In [52]:
df

key  value  rank
0    a    0.0   1.0
1    b    1.0   2.0
2    c    2.0   3.0
3    a    3.0   4.0
4    b    4.0   5.0
5    c    5.0   6.0
6    a    6.0   7.0
7    b    7.0   8.0
8    c    8.0   9.0
9    a    9.0  10.0
10   b   10.0  11.0
11   c   11.0  12.0

In [54]:
df1 = pd.DataFrame(np.random.randn(10))
df1['rank'] = df1.rank()
df1

0  rank
0  1.182047   9.0
1  0.575829   8.0
2 -0.173224   4.0
3  1.280405  10.0
4 -2.264432   1.0
5 -1.250905   2.0
6  0.516706   7.0
7  0.435208   6.0
8 -1.018026   3.0
9  0.303651   5.0

In [56]:
df['value'] * 2

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [60]:
df = df.drop(columns=['rank'])
df

key  value
0    a    0.0
1    b    1.0
2    c    2.0
3    a    3.0
4    b    4.0
5    c    5.0
6    a    6.0
7    b    7.0
8    c    8.0
9    a    9.0
10   b   10.0
11   c   11.0

In [61]:
df.groupby('key').transform(lambda x: x.rank(ascending=False))

value
0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0

In [81]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [78]:
df.groupby('key').transform(normalize)

value
0  -1.161895
1  -1.161895
2  -1.161895
3  -0.387298
4  -0.387298
5  -0.387298
6   0.387298
7   0.387298
8   0.387298
9   1.161895
10  1.161895
11  1.161895

In [80]:
df.groupby('key').apply(normalize)

ValueError: can only convert an array of size 1 to a Python scalar

In [3]:
arr = np.random.randn(4,3)
arr

array([[-1.54738088,  1.30764213,  0.03881985],
       [-0.17499776, -0.2781405 , -0.66578662],
       [-0.67798459, -1.49472633, -0.74748038],
       [-0.70939262, -0.81593971,  1.67872422]])

In [5]:
arr.mean(0), arr.mean(1)

(array([-0.77743896, -0.3202911 ,  0.07606927]),
 array([-0.06697297, -0.37297496, -0.9733971 ,  0.05113063]))

In [7]:
(arr - arr.mean(0)).mean(0)

array([  2.77555756e-17,   0.00000000e+00,   0.00000000e+00])

In [11]:
arr - arr.mean(1).reshape(4,1)

array([[-1.48040791,  1.3746151 ,  0.10579282],
       [ 0.1979772 ,  0.09483446, -0.29281166],
       [ 0.29541251, -0.52132923,  0.22591672],
       [-0.76052325, -0.86707034,  1.62759359]])

In [16]:
a = np.random.uniform(1, 10, 4)
a, a.shape

(array([ 9.49198273,  7.94691409,  7.89801379,  6.80041077]), (4,))

In [18]:
a = a[np.newaxis, :]
a, a.shape

(array([[[ 9.49198273,  7.94691409,  7.89801379,  6.80041077]]]), (1, 1, 4))

In [19]:
col = np.array([1,2,3,4])
col, col.shape

(array([1, 2, 3, 4]), (4,))

In [21]:
col[:, np.newaxis], col[:, np.newaxis].shape

(array([[1],
        [2],
        [3],
        [4]]), (4, 1))

In [23]:
a_c = np.random.randn(1000000).reshape(1000, 1000, order='C')
a_f = np.random.randn(1000000).reshape(1000, 1000, order='F')
a_c.flags, a_f.flags

(  C_CONTIGUOUS : True
   F_CONTIGUOUS : False
   OWNDATA : False
   WRITEABLE : True
   ALIGNED : True
   UPDATEIFCOPY : False,   C_CONTIGUOUS : False
   F_CONTIGUOUS : True
   OWNDATA : False
   WRITEABLE : True
   ALIGNED : True
   UPDATEIFCOPY : False)

In [28]:
%timeit a_c.sum(1)
%timeit a_f.sum(1)

591 µs ± 2.85 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
565 µs ± 3.26 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [27]:
%timeit a_c.sum(axis=0)
%timeit a_f.sum(axis=0)

561 µs ± 1.93 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
591 µs ± 2.19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
