In [ ]:
!pip install --upgrade tensorflow

In [1]:
import tensorflow as tf
tf.__version__

'1.3.0'

In [7]:
a = tf.Variable(10)
b = tf.Variable(20)
f = a * b + 100

sess = tf.Session()
sess.run(a.initializer)
sess.run(b.initializer)
sess.run(f)

300

In [8]:
with tf.Session() as sess:
    a.initializer.run()
    b.initializer.run()
    result = f.eval()
result

300

In [10]:
init = tf.global_variables_initializer
sess = tf.InteractiveSession()
init.run()
result = f.eval()
result

300

In [11]:
a.graph is tf.get_default_graph()

True

In [5]:
A = tf.placeholder(tf.float32, shape=(None, 3))
C = tf.placeholder(tf.float32, shape=(None, 3))
B = A * C
with tf.Session() as sess:
    B_val_1 = B.eval(feed_dict={A: [[1, 2, 3]], C:[[1,4,9]]})
    B_val_2 = B.eval(feed_dict={A: [[4,5,6],[7,8,9]], C:[[4,5,6],[7,8,9]]})
print(B_val_1)
print(B_val_2)

[[  1.   8.  27.]]
[[ 16.  25.  36.]
 [ 49.  64.  81.]]
