In [2]:
x = 10
y = 10
print (x + y)

20


In [3]:
while(x < 1000):
    x = x + 1
print (x)

1000


In [1]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
for n in range(10):
    print (n)
    pass
print('done')

0
1
2
3
4
5
6
7
8
9
done


In [6]:
print(2**3)

8


In [7]:
def calculateAmount(x, y):
    z = (x*y)/(x**y)
    return z


In [8]:
calculateAmount(3,4)

0.14814814814814814

In [9]:
calculateAmount(3.3,4.4)

0.07594606574442928

In [10]:
import numpy as np

In [11]:
a = np.zeros([3,2])
print(a)

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [16]:
b = np.random.randint(10, size=(3, 4))
print(b)
             

[[1 0 9 6]
 [0 8 5 2]
 [6 6 6 9]]


In [20]:
print(b)
print(b[:,1])
print(b[:,1])
print(b[:,0:1])
print(b[:1,0:1])

[[1 0 9 6]
 [0 8 5 2]
 [6 6 6 9]]
[0 8 6]
[0 8 6]
[[1]
 [0]
 [6]]
[[1]]


In [21]:
import matplotlib.pyplot as pl